### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by alexjfisher** [strider/puppet-rhnreg_ks#16]
@strider Any chance of a new forge release?  Thanks.

**Comment by alexjfisher** [comment]
@strider Any thoughts?  If you've moved on from puppet and need a new maintainer, the Vox Pupuli project would be pleased to help.

**Comment by strider** [comment]
@alexjfisher Hi Alex, I bumped the release 0.1.3 on the forge! sorry for the delay. Thanks for your patience.
